### ISSUE TITLE
Review zadání

### ISSUE THREAD

**Issue by janavitvar** [TomasKulhavy/2122ALG2-kulhavy-zapisnik-letu#1]
V problému popište pro koho a k čemu bude aplikace sloužit. Budou zápisníky pro jednotlivé typy letadel obsahovat různé údaje?

**Comment by TomasKulhavy** [comment]
Doplněno: https://github.com/TomasKulhavy/2122ALG2-kulhavy-zapisnik-letu/blob/master/README.md#popis-probl%C3%A9mu-motivace
